// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkTEQ1gWaFCrrVDbTmesyXTdbAlnH5Rp8',
    appId: '1:364314355243:web:1b717fe293adf42516ac6e',
    messagingSenderId: '364314355243',
    projectId: 'pos-umkm-4705f',
    authDomain: 'pos-umkm-4705f.firebaseapp.com',
    storageBucket: 'pos-umkm-4705f.firebasestorage.app',
    measurementId: 'G-WZHGHNSR1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTAoI77yu84kaIPg2Nx0RmryfHMNggXw',
    appId: '1:364314355243:android:685bf100a50fd1a616ac6e',
    messagingSenderId: '364314355243',
    projectId: 'pos-umkm-4705f',
    storageBucket: 'pos-umkm-4705f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiKnJF1h238tIwpwgS0r-fnGxPnEmzuyE',
    appId: '1:364314355243:ios:c45d01a0ee92aed416ac6e',
    messagingSenderId: '364314355243',
    projectId: 'pos-umkm-4705f',
    storageBucket: 'pos-umkm-4705f.firebasestorage.app',
    iosBundleId: 'com.example.erpUmkm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiKnJF1h238tIwpwgS0r-fnGxPnEmzuyE',
    appId: '1:364314355243:ios:c45d01a0ee92aed416ac6e',
    messagingSenderId: '364314355243',
    projectId: 'pos-umkm-4705f',
    storageBucket: 'pos-umkm-4705f.firebasestorage.app',
    iosBundleId: 'com.example.erpUmkm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkTEQ1gWaFCrrVDbTmesyXTdbAlnH5Rp8',
    appId: '1:364314355243:web:6010c73aa8d5582f16ac6e',
    messagingSenderId: '364314355243',
    projectId: 'pos-umkm-4705f',
    authDomain: 'pos-umkm-4705f.firebaseapp.com',
    storageBucket: 'pos-umkm-4705f.firebasestorage.app',
    measurementId: 'G-KPDHDVXJ9Z',
  );
}
